defaults: &defaults
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: jhb01

development:
  database: handy_rails_tips_development
  <<: *defaults
  
test:
  database: handy_rails_tips_test
  <<: *defaults
  
production:
  database: handy_rails_tips_production
  <<: *defaults