defaults: &defaults
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: root

development:
  database: handy_rails_tips_development
  <<: *defaults
  password: 
  
  
test:
  database: handy_rails_tips_test
  <<: *defaults
  password: 
  
  
production:
  database: handy_rails_tips_production
  <<: *defaults
  password: jhb01
  